import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react';
import styles from '../styles/Home.module.css'
export default function Home() {
const courses = [
  {
    name:"Android Application Development",
    brief:"Build and maintain good android applications",
    picture:"/img/android.png",
  },
  {
    name:"HTML And Css Website Development",
    brief:"Build modern responsive websites With HTML And Css",
    picture:"/img/computer.png",
  }
]
  return (
    <div className="padding-top-100">
      <Head>
        <title>Fun Techs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="home">
        <div>
        <div className='row'>
        <div className="col sm-12 md-12 lg-6">
          <div className='container padding-top-20'>
            <div>
              <div className='padding'>
              <h1 className='header h1'>Fun Techs: Join Today To Start Your Journey As A Developer</h1>
          <div>
            Build your skills, acquire knowedge, get your certificate and enter the job market with confidence.
          </div>
              </div>
          <div className='padding-top-20'>
          <a href="/register" className='inline-block margin'>
          <button className='button indigo text-white padding-20'>Register Now <i class="fas fa-angle-right"></i></button>
          </a>
          <a href="#"  className='inline-block margin'>
          <span className='text-larger text-indigo indigo-border padding-20 hover-light'> Our Courses </span>
          </a>
          </div>
            </div>
          </div>
        </div>
        <div className="col sm-12 md-12 lg-6">
          <div className='container padding'>
           <img src='/img/home.png'  className='responsive'/>
          </div>
        </div>
      </div>
        </div>     
        </div>

 <div>
   <div className='container design'>
     <div className='h1 text-indigo header padding'>Popular Courses</div>
     <div className='row'>
       <div className="col sm-12 md-8 lg-8">
       <div className='h4 padding'>
       Take Chance today to become successful tomorrow, enroll in our course to become certified
     </div>
         </div>
    </div>

     <div className='row'>
       {
         courses.map(course=>(
          <div className='col sm-12 md-6 lg-6 padding' key={course.name}>
          <div className='padding card course-card pointer hover-shadow'>
           <div className='course-logo card fit-width fit-height padding round-edge hover-up pointer'>
             <img src={course.picture} className='width-100' />
           </div>
           <div className='container'>
           <div className='h4 section'>{course.name}</div>
           <div className='section'>{course.brief}</div>
           <div className='section'>
             <a href=''>
               <button className='button indigo card text-white'>
                 Enroll Course <i class="fas fa-arrow-right"></i>
               </button>
             </a>
            </div>
          </div>
          </div>
    
        </div>
         ))
       }
     </div>
   </div>
 </div>
    </div>
  )
}
